# Generated by Django 4.2.7 on 2023-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('foto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nombre_autor', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('genero', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('disponible', models.CharField(max_length=200)),
                ('portada', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
    ]
