# Generated by Django 4.2.7 on 2023-12-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='valoracion',
            field=models.FloatField(default=0),
        ),
    ]
