# Generated by Django 4.2.7 on 2023-12-17 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_libro_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='libro',
            name='valoracion_libro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion_por_usuario', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
