# Generated by Django 4.2.7 on 2023-12-17 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_libro_valoracion_libro_valoracion_libro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='valoracion_libro',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='valoracion_por_usuario',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
